export interface BlueprintPin {
  id: string
  name: string
  friendlyName: string
  direction: 'input' | 'output'
  type: { category: string; subcategory: string; object: string; container: string; [key: string]: unknown }
  defaultValue: string
  autogeneratedDefault: string
  defaultObject: string
  defaultText: string
  flags: number
  links: Array<{ node?: string; nodeName?: string; pin: string; export?: number }>
  [key: string]: unknown
}
export interface BlueprintNode {
  id: string
  exportIndex: number
  name: string
  classPath: string
  title: string
  x: number
  y: number
  width: number
  height: number
  comment: string
  complete: boolean
  properties: Record<string, unknown>
  pins: BlueprintPin[]
}
export interface BlueprintGraph {
  id: string
  name: string
  path: string
  complete: boolean
  diagnostics: string[]
  nodes: BlueprintNode[]
}
export interface BlueprintDocument {
  schemaVersion: 1
  readerVersion?: number
  assetClass?: string
  status: 'complete' | 'partial' | 'unsupported'
  engineVersion: string
  graphs: BlueprintGraph[]
  diagnostics: string[]
}
export interface BlueprintSide {
  ref: string
  path: string
  status: 'ready' | 'absent' | 'unavailable'
  reason?: string
  contentHash?: string
  documentKey?: string
  document?: BlueprintDocument
}
export interface BlueprintRequest {
  knownDocuments?: string[]
  force?: boolean
  filePath: string
  oldPath?: string
  leftRef: string
  rightRef: string
  requestId: string
}
export interface BlueprintComparison { left: BlueprintSide; right: BlueprintSide }
